### ISSUE TITLE
What is the purpose of change_detector.rb?

### ISSUE THREAD

**Issue by voxik** [floehopper/introspection#2]
Hello,

Could you please elaborate what is purpose of the change_detector.rb? I am trying to package your gem for Fedora, and it seems that this file pulls in instantiator gem. I would like to avoid this dependency, since the change_detector.rb seems to be useless ATM, but I am not sure.

Vit

**Comment by floehopper** [comment]
@voxik: Sorry for the ridiculously slow (!) response to your question. I have just removed change_detector.rb and the dependency on instantiator.
